2023-10-18 21:43:13.578 [info] [Error - 21:43:13] Client Python Jedi: connection to server is erroring. Shutting down server.
2023-10-18 21:43:13.581 [info] [Error - 21:43:13] Stopping server failed
2023-10-18 21:43:13.581 [info] Error: Client is not running and can't be stopped. It's current state is: starting
	at E.shutdown (/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2080806)
	at E.stop (/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2080387)
	at E.stop (/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2242667)
	at E.handleConnectionError (/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/out/client/extension.js:2:2086894)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-10-18 21:43:13.585 [info] [Error - 21:43:13] Server initialization failed.
2023-10-18 21:43:13.585 [info]   Message: write EPIPE
  Code: -32099 
2023-10-18 21:43:13.586 [info] [Error - 21:43:13] Python Jedi client: couldn't create connection to server.
2023-10-18 21:43:13.586 [info]   Message: write EPIPE
  Code: -32099 
2023-10-18 21:43:13.616 [info] [Info  - 21:43:13] Connection to server got closed. Server will restart.
2023-10-18 21:43:13.617 [info] true
2023-10-18 21:43:13.740 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 21:43:14.009 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 21:43:14.018 [info] [Error - 21:43:14] Server initialization failed.
2023-10-18 21:43:14.018 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:14.018 [info] [Info  - 21:43:14] Connection to server got closed. Server will restart.
2023-10-18 21:43:14.018 [info] true
2023-10-18 21:43:14.020 [info] [Error - 21:43:14] Python Jedi client: couldn't create connection to server.
2023-10-18 21:43:14.020 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:14.438 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 21:43:14.443 [info] [Error - 21:43:14] Server initialization failed.
2023-10-18 21:43:14.443 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:14.443 [info] [Info  - 21:43:14] Connection to server got closed. Server will restart.
2023-10-18 21:43:14.444 [info] true
2023-10-18 21:43:14.444 [info] [Error - 21:43:14] Python Jedi client: couldn't create connection to server.
2023-10-18 21:43:14.444 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:14.445 [info] [Error - 21:43:14] Restarting server failed
2023-10-18 21:43:14.446 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:15.065 [info] [Error - 21:43:15] Server initialization failed.
2023-10-18 21:43:15.066 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:15.066 [info] [Info  - 21:43:15] Connection to server got closed. Server will restart.
2023-10-18 21:43:15.066 [info] true
2023-10-18 21:43:15.066 [info] [Error - 21:43:15] Python Jedi client: couldn't create connection to server.
2023-10-18 21:43:15.066 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:15.066 [info] [Error - 21:43:15] Restarting server failed
2023-10-18 21:43:15.072 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:15.257 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 21:43:15.402 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 21:43:15.435 [info] [Error - 21:43:15] Server initialization failed.
2023-10-18 21:43:15.436 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:15.436 [info] [Error - 21:43:15] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-18 21:43:15.438 [info] [Error - 21:43:15] Python Jedi client: couldn't create connection to server.
2023-10-18 21:43:15.438 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 21:43:15.445 [info] [Error - 21:43:15] Restarting server failed
2023-10-18 21:43:15.445 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
