2023-10-18 22:04:27.109 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:04:27.169 [info] [Error - 22:04:27] Server initialization failed.
2023-10-18 22:04:27.170 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:27.170 [info] [Info  - 22:04:27] Connection to server got closed. Server will restart.
2023-10-18 22:04:27.170 [info] true
2023-10-18 22:04:27.187 [info] [Error - 22:04:27] Python Jedi client: couldn't create connection to server.
2023-10-18 22:04:27.187 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:27.590 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:04:27.595 [info] [Error - 22:04:27] Server initialization failed.
2023-10-18 22:04:27.595 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:27.595 [info] [Info  - 22:04:27] Connection to server got closed. Server will restart.
2023-10-18 22:04:27.595 [info] true
2023-10-18 22:04:27.625 [info] [Error - 22:04:27] Python Jedi client: couldn't create connection to server.
2023-10-18 22:04:27.625 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:28.036 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:04:28.054 [info] [Error - 22:04:28] Server initialization failed.
2023-10-18 22:04:28.054 [info]   Message: Cannot call write after a stream was destroyed
  Code: -32099 
2023-10-18 22:04:28.056 [info] [Error - 22:04:28] Python Jedi client: couldn't create connection to server.
2023-10-18 22:04:28.056 [info]   Message: Cannot call write after a stream was destroyed
  Code: -32099 
2023-10-18 22:04:28.057 [info] [Error - 22:04:28] Restarting server failed
2023-10-18 22:04:28.057 [info]   Message: Cannot call write after a stream was destroyed
  Code: -32099 
2023-10-18 22:04:28.057 [info] [Error - 22:04:28] Restarting server failed
2023-10-18 22:04:28.057 [info]   Message: Cannot call write after a stream was destroyed
  Code: -32099 
2023-10-18 22:04:28.059 [info] [Info  - 22:04:28] Connection to server got closed. Server will restart.
2023-10-18 22:04:28.059 [info] true
2023-10-18 22:04:28.225 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:04:28.246 [info] [Error - 22:04:28] Server initialization failed.
2023-10-18 22:04:28.246 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:28.247 [info] [Info  - 22:04:28] Connection to server got closed. Server will restart.
2023-10-18 22:04:28.247 [info] true
2023-10-18 22:04:28.335 [info] [Error - 22:04:28] Python Jedi client: couldn't create connection to server.
2023-10-18 22:04:28.335 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:28.390 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:04:28.409 [info] [Error - 22:04:28] Server initialization failed.
2023-10-18 22:04:28.409 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:28.409 [info] [Error - 22:04:28] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-18 22:04:28.422 [info] [Error - 22:04:28] Python Jedi client: couldn't create connection to server.
2023-10-18 22:04:28.422 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:04:28.423 [info] [Error - 22:04:28] Restarting server failed
2023-10-18 22:04:28.423 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.180 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-18 22:05:39.181 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:05:39.189 [info] [Error - 22:05:39] Server initialization failed.
2023-10-18 22:05:39.189 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.189 [info] [Info  - 22:05:39] Connection to server got closed. Server will restart.
2023-10-18 22:05:39.190 [info] true
2023-10-18 22:05:39.209 [info] [Error - 22:05:39] Python Jedi client: couldn't create connection to server.
2023-10-18 22:05:39.210 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.250 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>
    from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:05:39.257 [info] [Error - 22:05:39] Server initialization failed.
2023-10-18 22:05:39.258 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.258 [info] [Info  - 22:05:39] Connection to server got closed. Server will restart.
2023-10-18 22:05:39.258 [info] true
2023-10-18 22:05:39.274 [info] [Error - 22:05:39] Python Jedi client: couldn't create connection to server.
2023-10-18 22:05:39.275 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.326 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-18 22:05:39.327 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:05:39.339 [info] [Error - 22:05:39] Server initialization failed.
2023-10-18 22:05:39.339 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.339 [info] [Info  - 22:05:39] Connection to server got closed. Server will restart.
2023-10-18 22:05:39.339 [info] true
2023-10-18 22:05:39.359 [info] [Error - 22:05:39] Python Jedi client: couldn't create connection to server.
2023-10-18 22:05:39.360 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.360 [info] [Error - 22:05:39] Restarting server failed
2023-10-18 22:05:39.360 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.415 [info] Traceback (most recent call last):

2023-10-18 22:05:39.416 [info]   File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-18 22:05:39.418 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:05:39.430 [info] [Error - 22:05:39] Server initialization failed.
2023-10-18 22:05:39.430 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.430 [info] [Info  - 22:05:39] Connection to server got closed. Server will restart.
2023-10-18 22:05:39.430 [info] true
2023-10-18 22:05:39.446 [info] [Error - 22:05:39] Python Jedi client: couldn't create connection to server.
2023-10-18 22:05:39.449 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.450 [info] [Error - 22:05:39] Restarting server failed
2023-10-18 22:05:39.450 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.501 [info] Traceback (most recent call last):
  File "/home/dodecaneser/.vscode-oss/extensions/ms-python.python-2023.18.0-universal/pythonFiles/run-jedi-language-server.py", line 9, in <module>

2023-10-18 22:05:39.501 [info]     from jedi_language_server.cli import cli
ModuleNotFoundError: No module named 'jedi_language_server'

2023-10-18 22:05:39.513 [info] [Error - 22:05:39] Server initialization failed.
2023-10-18 22:05:39.513 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.513 [info] [Error - 22:05:39] The Python Jedi server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-10-18 22:05:39.514 [info] [Error - 22:05:39] Python Jedi client: couldn't create connection to server.
2023-10-18 22:05:39.514 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-10-18 22:05:39.514 [info] [Error - 22:05:39] Restarting server failed
2023-10-18 22:05:39.515 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
